### ISSUE TITLE
[question] When will the debug tool be available?

### ISSUE THREAD

**Issue by joehoeller** [NVIDIA/tensorflow-determinism#1]

**Comment by duncanriach** [comment]
Because of my focus on deploying/upstreaming solutions to TensorFlow non-determinism and because priorities related to that keep shifting, I can't guarantee when this will be available. I can tell you that it's rapidly approaching the front of the queue.

**Comment by duncanriach** [comment]
I'm assuming, and assumed, that "this" in the question was referring to the debug tool and not any of the other features that have been or will be released via this repo. This question has been answered. Closing.
